exports.sizeInBytes= (string)=>{return Buffer.from(string).length}




exports.REGISTRATION_TIMEOUT_HOURS=1
exports.REGISTRATION_TIMEOUT_MINS=exports.REGISTRATION_TIMEOUT_HOURS*60
exports.REGISTRATION_TIMEOUT_SECS=exports.REGISTRATION_TIMEOUT_HOURS*3600
exports.REGISTRATION_TIMEOUT_MILLIS=exports.REGISTRATION_TIMEOUT_MINS*3600000

exports.PASSWORD_RESET_TIMEOUT_HOURS=1/6
exports.PASSWORD_RESET_TIMEOUT_MINS=exports.REGISTRATION_TIMEOUT_HOURS*60
exports.PASSWORD_RESET_TIMEOUT_SECS=exports.REGISTRATION_TIMEOUT_HOURS*3600
exports.PASSWORD_RESET_TIMEOUT_MILLIS=exports.REGISTRATION_TIMEOUT_MINS*3600000

exports.LOGIN_TIMEOUT_HOURS=1
exports.LOGIN_TIMEOUT_MINS=exports.LOGIN_TIMEOUT_HOURS*60
exports.LOGIN_TIMEOUT_SECS=exports.LOGIN_TIMEOUT_HOURS*3600
exports.LOGIN_TIMEOUT_MILLIS=exports.LOGIN_TIMEOUT_HOURS*3600000  
